### PR TITLE
Removed `phpdbg`, added `pcov` dependency as part of the build

### LINKED ISSUE #130: Remove `phpdbg`, migrate to `pcov`
See https://github.com/sebastianbergmann/php-code-coverage/issues/945

According to upstream maintainers, `phpdbg` coverage support is not really maintained, and we should therefore migrate away from it.

We will likely need to ship `pcov` with our container, and use that for running tests.

We may also need to remove `phpdbg`, since running `phpdbg` with `pcov` installed leads to segfaults.

### PR DESCRIPTION
**Pull request by Ocramius**
This is a potential breaking change, but note that PHPUnit v10 no longer supports PHPDBG for coverage, which was the only use-case for PHPDBG in this container, thus far.

We instead install `pcov`, which is considered precise enough for coverage reports by PHPUnit.

Fixes #130

Ref: https://github.com/laminas/laminas-continuous-integration-action/issues/130
Ref: https://github.com/sebastianbergmann/php-code-coverage/issues/945
Ref: https://github.com/sebastianbergmann/php-code-coverage/commit/c304be7d8aa00a71cf8fe763a4b92e14d3f67f4d

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | yes (?)
| New Feature   | yes
| RFC           | no
| QA            | yes

Only question here is:

 * do we release on `1.33.0`?
 * do we release on `2.0.0`?

### CODE REVIEW

**Comment by Ocramius** [comment]
```
 #13 36.03 E: Unable to locate package php5.6-pcov
#13 36.03 E: Couldn't find any package by glob 'php5.6-pcov'
#13 36.03 E: Unable to locate package php7.0-pcov
#13 36.03 E: Couldn't find any package by glob 'php7.0-pcov'
```

Nnnnngh... gonna revert for those two...

**Comment by internalsystemerror** [comment]
I'm guessing we can't use PHPUnit 10 on those PHP versions anyway. `2.0.0` sounds like the safer bet for people who are actively using this.

**Review by internalsystemerror — APPROVED** [review]

**Comment by gsteel** [comment]
I'm in favour of 1.33.0 FWIW - It's just a change in dependencies rather than an alteration to behaviour. The action will still do all of the things it was supposed to, in effectively the same way right?

File: entrypoint.sh [hunk 1]
```diff
@@ -188,7 +187,6 @@ fi
 if [[ "${INI}" != "" ]];then
     echo "Installing php.ini settings"
     echo "$INI" > "/etc/php/${PHP}/cli/conf.d/99-settings.ini"
-    echo "$INI" > "/etc/php/${PHP}/phpdbg/conf.d/99-settings.ini"
```
Comment (gsteel) [inline entrypoint.sh:191]: Question: does `phpdbg` itself use this specific directory?

**Review by gsteel — APPROVED** [review]

**Comment by internalsystemerror** [comment]
> The action will still do all of the things it was supposed to, in effectively the same way right?

If you were depending on phpdbg before, you won't be able to now.

**Comment by boesing** [comment]
https://github.com/laminas/laminas-continuous-integration-action/issues/130#issuecomment-1439848951

**Comment by Ocramius** [comment]
This will go to `2.0.0`, but I need to verify that `pcov` is enabled by default, before merging.

File: entrypoint.sh (hunk 1 above)
Comment (Ocramius) [reply entrypoint.sh:191]: Yep, it has its own config dir.

**Comment by Ocramius** [comment]
Since @lcobucci is starting to get blocked by this quite a bit, I'm trying to push it forward :-)
