### PR TITLE
Ensure newlines are propagated to php.ini settings

### LINKED ISSUE #7: Syntax error with ini values in laminas-ci.json
I'm having some issues with adding ini values to `.laminas-ci.json` - I can't figure out why, but it appears that all the ini values are getting joined to a single line with spaces instead of a new line.

With some test json, running the below on my local machine does exactly what it's supposed to - each element is joined with \n as you'd expect, but still I have "Syntax error, unexpected =" when PHP parses the 99-settings.ini in CI.

https://github.com/laminas/laminas-continuous-integration-action/blob/92f18a56222df7f3d1896de178b6c0531c1af5a0/entrypoint.sh#L128

So far, I've tried 
- `cat path/to/99-settings.ini` to inspect the .ini file to verify the issue
- tried adding extra empty strings in the list of ini values ["foo=bar", "", "other=baz"]
- tried just a single ini setting  - ["foo=bar"]

I can see that the matrix action is sending sane JSON with a prepended `memory_limit=-1` and everything was working fine just a few day ago 🤷‍♂️

### PR DESCRIPTION
**Pull request by weierophinney**
Bash does not like to capture newlines into variables.  As such, this patch concatenates php.ini settings using the string `{NL}`, which is then translated to a newline when pushing to the php.ini settings file.

Fixes #7

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -151,7 +151,7 @@ fi
 
 if [[ "${INI}" != "" ]];then
     echo "Installing php.ini settings"
-    echo $INI > /etc/php/${PHP}/cli/conf.d/99-settings.ini
+    echo $INI | sed "s/{NL}/\n/g" > /etc/php/${PHP}/cli/conf.d/99-settings.ini
```
Comment (glensc) [inline entrypoint.sh:154]: this is a super dumb "fix", now values can't contain `{NL}`!
bash has no problems containing newlines!

sending PR with actual fix with quoting echo arguments!

Comment (glensc) [reply entrypoint.sh:154]: https://github.com/laminas/laminas-continuous-integration-action/pull/16/files

Comment (boesing) [reply entrypoint.sh:154]: 1st of all: there is nothing dumb when not having *all* scenarios in mind
2nd: you might want to learn how to communicate such problems
